# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: your name
  description: |
    Cross-platform ansible role for ssh daemon configration.
  company: your company (optional)
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: MacOSX
      versions:
        - 10.12
        - 10.13
    - name: Debian
      versions:
        - all
    - name: LibreELEC
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - ssh
    - sshd
    - secure_shell
dependencies:
  - role: common
    tags:
      - ssh_daemon_cfg
      - ssh_daemon_cfg_general
      - ssh_daemon_cfg_users
